# Generated by Django 2.2 on 2020-01-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='classfied',
            new_name='classified',
        ),
    ]
